name: 'Checkout, Setup, Node, Yarn Install'
author: 'Brian Espinosa'
description: 'Composite action that will check out our code, set up node and yarn with caching, and install yarn dependencies'

branding:
  icon: 'download-cloud'
  color: 'green'

runs:
  using: "composite"

  steps:
    # https://github.com/actions/checkout#usage
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # https://github.com/actions/setup-node#usage
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version-file: ".nvmrc"
        cache: "yarn"
        cache-dependency-path: |
          **/*.lock
          yarn.lock

    - run: yarn install --immutable
      shell: bash
      
